### PR TITLE
switch to sssom converter

### LINKED ISSUE #35: Instead of obo_converter, use the SSSOM EPM directly
For context see: https://github.com/monarch-initiative/monarch-gene-mapping/pull/34#discussion_r1416046747

```
pip install sssom
```

```
from sssom.context import get_converter
converter = get_converter()
```

@glass-ships does this work for you? This will use the correct complete and SSSOM aligned obo converter.

### PR DESCRIPTION
**Pull request by glass-ships**
Closes #35

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
It looks good, but i assume you are also checking that the resulting data frames look ok, in particular that nothing important is lost

**Comment by glass-ships** [comment]
There are in fact still some subject_id's missing, potentially values i may have missed (it's almost a million rows):
image

**Comment by matentzn** [comment]
@glass-ships can you prioritise finishing this, because right now the gene mappings on data.mi.org are totally broken; 

I think we should not upload anything to data.mi.org unless it passes first through mapping commons..

**Comment by matentzn** [comment]
> unfortunately I have no idea how to fix this without knowing why there are still empty column values using the newly suggested converter


I provided a skeleton for the solution in my last commit. All you need to do is add the missing prefixes to the prefix_map!

**Comment by glass-ships** [comment]
i'm not sure what the urls on the other side of each mapping should be - suggestions for where to look?

**Comment by matentzn** [comment]
For now, just to make it work: use something monarchy like data.mi.org. We will correct this later. So https://data.monarchinitive.org/sources/X/, where X is the prefix

**Pull request merged**
